# Generated by Django 2.1.5 on 2022-06-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0002_song_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='year_release',
            field=models.DateTimeField(),
        ),
    ]
