# Generated by Django 2.1.5 on 2022-06-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0003_auto_20220609_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='date_upload',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='year_release',
            field=models.DateField(),
        ),
    ]
