# Generated by Django 2.1.5 on 2022-06-09 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0006_auto_20220609_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='genre_img',
        ),
    ]
