# Generated by Django 2.1.5 on 2022-06-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0008_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='img',
        ),
        migrations.AddField(
            model_name='type',
            name='image',
            field=models.FileField(default='', upload_to='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
