# Generated by Django 2.1.5 on 2022-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0010_auto_20220610_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('USA', 'USA'), ('UK', 'UK'), ('Ghana', 'Ghana'), ('Canada', 'Canada')], default='', max_length=8),
            preserve_default=False,
        ),
    ]
