# Generated by Django 2.1.5 on 2022-06-10 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0013_auto_20220610_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='song',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='title_like', to='audio.Song'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
