# Generated by Django 2.1.5 on 2022-06-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0017_auto_20220610_2137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='like',
        ),
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
