# Generated by Django 2.1.5 on 2022-06-12 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audio', '0018_auto_20220611_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='like',
        ),
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.ManyToManyField(blank=True, default=0, related_name='song_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
