# Generated by Django 2.1.5 on 2022-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audio', '0019_auto_20220612_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='like',
        ),
        migrations.AddField(
            model_name='song',
            name='like',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
